import { describe, expect, it } from 'vitest'
import type { PanoramaProjectionMetadata } from '../types'
import {
  panoramaUvToLocalDirection,
  panoramaUvToSpherePosition,
  projectDatasetPointToPanorama,
  projectFrameLocalPointToPanorama,
} from './panoramaProjection'

const METADATA: PanoramaProjectionMetadata = {
  frame_id: 'frame-1',
  coordinate_space: 'dataset',
  projection: 'normalized_equirectangular',
  origin: [100, 200, 10],
  forward: [0, 1, 0],
  right: [1, 0, 0],
  up: [0, 0, 1],
  yaw_offset_deg: 0,
  pitch_offset_deg: 0,
}

describe('panorama point projection', () => {
  it('matches the server equirectangular axis convention', () => {
    expect(projectFrameLocalPointToPanorama([0, 10, 0], METADATA)).toEqual({
      u: 0.5,
      v: 0.5,
      depth: 10,
    })
    expect(projectFrameLocalPointToPanorama([10, 0, 0], METADATA)).toEqual({
      u: 0.75,
      v: 0.5,
      depth: 10,
    })
    expect(projectFrameLocalPointToPanorama([-10, 0, 0], METADATA)).toEqual({
      u: 0.25,
      v: 0.5,
      depth: 10,
    })
  })

  it('subtracts the dataset origin and rejects the camera origin', () => {
    expect(projectDatasetPointToPanorama([100, 210, 10], METADATA)?.u).toBe(0.5)
    expect(projectDatasetPointToPanorama([100, 200, 10], METADATA)).toBeNull()
  })

  it('converts normalized panorama UV into the inward sphere location', () => {
    const position = panoramaUvToSpherePosition(0.5, 0.5, 10)
    expect(position?.[0]).toBeCloseTo(-10)
    expect(position?.[1]).toBeCloseTo(0)
    expect(position?.[2]).toBeCloseTo(0)
  })

  it('matches a non-axis Python projection golden vector', () => {
    // Generated by geometry.build_camera_axes/apply_panorama_angular_offsets/
    // project_points_equirectangular. This catches axis ordering and sign drift.
    const metadata: PanoramaProjectionMetadata = {
      frame_id: 'python-golden',
      coordinate_space: 'dataset',
      projection: 'normalized_equirectangular',
      origin: [0, 0, 0],
      forward: [0.2513908552200246, 0.5704266631901495, 0.7819309815025215],
      right: [0.9438822364991671, -0.32328659609298477, -0.06761730849376985],
      up: [-0.21421708973159675, -0.7550491366185139, 0.6196868884836615],
      yaw_offset_deg: 7.5,
      pitch_offset_deg: -3.25,
    }
    const projected = projectFrameLocalPointToPanorama([12.5, -4.25, 3.75], metadata)
    expect(projected?.u).toBeCloseTo(0.7061724312999704, 12)
    expect(projected?.v).toBeCloseTo(0.43329805654137143, 12)
    expect(projected?.depth).toBeCloseTo(13.724977231310804, 12)
  })

  it('round-trips projected axes through the Three sphere UV convention', () => {
    const point: [number, number, number] = [3, 8, 4]
    const projected = projectFrameLocalPointToPanorama(point, METADATA)
    expect(projected).not.toBeNull()
    const direction = panoramaUvToLocalDirection(projected!.u, projected!.v)
    const depth = Math.hypot(...point)
    expect(direction?.[0]).toBeCloseTo(point[0] / depth, 12)
    expect(direction?.[1]).toBeCloseTo(point[2] / depth, 12)
    expect(direction?.[2]).toBeCloseTo(point[1] / depth, 12)

    const sphere = panoramaUvToSpherePosition(projected!.u, projected!.v, 1)
    expect(sphere?.[0]).toBeCloseTo(-point[1] / depth, 12)
    expect(sphere?.[1]).toBeCloseTo(point[2] / depth, 12)
    expect(sphere?.[2]).toBeCloseTo(-point[0] / depth, 12)
  })
})
